# Generated by Django 4.2 on 2023-04-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(choices=[('Da', 'Dawn'), ('LM', 'Late Morning'), ('M', 'Midday'), ('EE', 'Early Evening'), ('ME', 'Mid Evening'), ('Du', 'Dusk')], default='Da', max_length=2)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.finch')),
            ],
        ),
    ]
