# Generated by Django 4.2 on 2023-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_location_sighting_time_alter_sighting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Finch Sighting'),
        ),
    ]
